version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  location-processing:
    build: ./location-processing
    ports:
      - 8002:8002
  users:
    build: ./users
    ports:
      - 8001:8001
    