{{ if eq ((.Values).type) "kubernetes" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    {{- include "service.ports" . | nindent 4 }}
  selector:
    {{- include "app.labels" . | nindent 4 -}}
{{ end }}
