version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.1.3

setup: true

workflows:
  path-filtering:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/path-filtering.yml
          mapping: |
            users/.* service "users"
            location-processing/.* service "location-processing"
            proto/.* all true