version: 2.1

executors:
  golang:
    docker:
      - image: golang:1.19.2-alpine
  base:
    docker:
      - image: cimg/base:2023.02
  helm:
    docker:
      - image: dtzar/helm-kubectl

parameters:
  directory:
    type: string
    default: ""
  all:
    type: boolean
    default: false
  chart:
    type: string
    default: deployment-chart

commands:
  docker_authenticate:
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: docker login -u${DOCKER_USER} ${DOCKER_SERVER} -p${DOCKER_PASSWORD}
  build-binary:
    parameters:
      directory:
        type: string
    steps:
      - run: ./build.sh <<parameters.directory>>
      - persist_to_workspace:
          root: .
          paths:
            - ./<<parameters.directory>>/bin/<<parameters.directory>>
  build-image:
    parameters:
      directory:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp /tmp/workspace/<<parameters.directory>> <<parameters.directory>>
          cd <<parameters.directory>>
          docker build . -t ${DOCKER_SERVER}/${DOCKER_REPOSITORY}/<<parameters.directory>>:${CIRCLE_SHA1}
      - run:
          name: Archive Docker image
          command: docker save --output image-<<parameters.directory>>.tar "${DOCKER_SERVER}/${DOCKER_REPOSITORY}/<<parameters.directory>>:${CIRCLE_SHA1}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image-<<parameters.directory>>.tar
  publish:
    parameters:
      directory:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: docker load --input /tmp/workspace/image-<<parameters.directory>>.tar
      - run:
          name: Publish Docker image
          command: docker push ${DOCKER_SERVER}/${DOCKER_REPOSITORY}/<<parameters.directory>>:${CIRCLE_SHA1}
  helm-validate:
    steps:
      - run: 
          name: Helm template
          command: helm template test chart/${CIRCLE_PROJECT_REPONAME} -f chart/example.yaml
  helm-release:
    steps:
      - run:
          name: Helm package
          command: helm package chart/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Helm Publish
          command: |
            VERSION=$(grep 'version ' chart/${CIRCLE_PROJECT_REPONAME}/Chart.yaml | awk '{print $3}')
            curl -umilan.jecmenica@gmail.com:${DOCKER_PASSWORD} -T ${CIRCLE_PROJECT_REPONAME}-${VERSION}.tgz "https://totalbot123demo.jfrog.io/artifactory/golang-helm/${CIRCLE_PROJECT_REPONAME}-${VERSION}.tgz"

# Define the jobs we want to run for this project
jobs:
  build-binary:
    executor: golang
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - build-binary:
          directory: <<parameters.directory>>
  build-image:
    executor: base
    parameters:
      directory:
        type: string
    steps:
      - docker_authenticate
      - checkout
      - build-image:
          directory: <<parameters.directory>>
  publish:
    executor: base
    parameters:
      directory:
        type: string
    steps:
      - docker_authenticate
      - publish:
          directory: <<parameters.directory>>
  test-chart:
    executor: helm
    steps:
      - checkout
      - helm-validate
  release-chart:
    executor: helm
    steps:
      - checkout
      - helm-release
  
    
workflows:
  all:
    when: 
      or: 
        - << pipeline.parameters.all >> 
    jobs:
      - build-binary:
          directory: proto

  users:
    when: 
      or: 
        - equal: [ users, << pipeline.parameters.directory >> ]
        - << pipeline.parameters.all >> 
    jobs:
      - build-binary:
          directory: users
      - build-image:
          directory: users
          requires:
            - build-binary
      - publish:
          directory: users
          requires:
            - build-image
      
  location-processing:
    when: 
      or: 
        - equal: [ location-processing, << pipeline.parameters.directory >> ]
        - << pipeline.parameters.all >> 
    jobs:
      - build-binary:
          directory: location-processing
      - build-image:
          directory: location-processing
          requires:
            - build-binary
      - publish:
          directory: location-processing
          requires:
            - build-image

  chart:
    jobs:
      - test-chart
      - release-chart:
          context:
            - Artifactory
          requires:
            - test-chart
          filters:
            branches:
              only:
                - master
